plugins {
    id 'com.android.application'
}

android {
    namespace 'com.fc32s1.control'
    compileSdk 35

    defaultConfig {
        applicationId 'com.fc32s1.control'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.github.mik3y:usb-serial-for-android:3.11.0'
}
